export type PublicScreen = {
  slug: string;
  title: string;
  query: string;
  summary: string;
  criteria: string[];
  category: "value" | "income" | "growth" | "momentum" | "quality" | "pullback";
};

export const PUBLIC_SCREENS: PublicScreen[] = [
  { slug:"quality-compounders", title:"Quality compounders", query:"Companies with ROIC above 15%, operating margin above 15%, and 3-year revenue growth above 8%", summary:"Durable businesses combining efficient capital allocation, healthy margins, and sustained top-line growth.", criteria:["ROIC above 15%","Operating margin above 15%","3-year revenue growth above 8%"], category:"quality" },
  { slug:"high-roic-companies", title:"High ROIC companies", query:"Companies with ROIC above 20%, ranked by ROIC", summary:"Looks for businesses generating strong returns on the capital invested in their operations.", criteria:["ROIC above 20%","Ranked by ROIC","Long-term fundamental quality"], category:"quality" },
  { slug:"high-fcf-yield", title:"High free-cash-flow yield", query:"Companies with free cash flow yield above 5% and positive operating margins", summary:"Finds companies producing meaningful free cash flow relative to their market value.", criteria:["FCF yield above 5%","Positive operating margin","Cash-flow valuation focus"], category:"value" },
  { slug:"strong-balance-sheets", title:"Strong balance sheets", query:"Companies with debt to equity below 0.5 and interest coverage above 8", summary:"A financial-resilience screen emphasizing lower leverage and a strong ability to service interest expense.", criteria:["Debt/equity below 0.5","Interest coverage above 8x","Balance-sheet quality"], category:"quality" },
  { slug:"profitable-growth", title:"Profitable growth", query:"Companies with 3-year revenue growth above 12%, 3-year EPS growth above 12%, and operating margin above 10%", summary:"Looks for sustained growth in both sales and earnings while requiring an established level of profitability.", criteria:["3-year revenue growth above 12%","3-year EPS growth above 12%","Operating margin above 10%"], category:"growth" },
  { slug:"reasonably-priced-quality", title:"Reasonably priced quality", query:"Companies with ROIC above 15%, free cash flow yield above 3%, and EV to EBITDA below 18", summary:"Combines business quality with cash generation and a ceiling on enterprise-value valuation.", criteria:["ROIC above 15%","FCF yield above 3%","EV/EBITDA below 18"], category:"value" },
  { slug:"cheap-large-cap-stocks", title:"Cheap large-cap stocks", query:"Large-cap stocks with a P/E under 15, cheapest first", summary:"A simple value screen for larger companies trading at relatively low earnings multiples.", criteria:["Large market capitalization","P/E below 15","Ranked from lower to higher P/E"], category:"value" },
  { slug:"high-dividend-low-volatility-stocks", title:"High-dividend, low-volatility stocks", query:"Dividend stocks yielding over 3% with beta below 1", summary:"Looks for income-producing companies whose shares have historically moved less than the broad market.", criteria:["Dividend yield above 3%","Beta below 1","Daily-refreshed stock universe"], category:"income" },
  { slug:"growing-stocks-near-52-week-lows", title:"Growing stocks near 52-week lows", query:"Companies with positive revenue growth trading more than 20% below their 52-week highs", summary:"A pullback screen for companies that are still growing revenue while their share prices sit well below recent highs.", criteria:["Positive revenue growth","At least 20% below the 52-week high","No recommendation layer"], category:"pullback" },
  { slug:"high-growth-reasonable-valuation", title:"High growth at a reasonable valuation", query:"Companies growing revenue more than 20% with a P/E under 30", summary:"Combines strong top-line growth with a valuation ceiling instead of screening on growth alone.", criteria:["Revenue growth above 20%","P/E below 30","Editable thresholds in Parse"], category:"growth" },
  { slug:"oversold-large-cap-stocks", title:"Oversold large-cap stocks", query:"Large-cap stocks with RSI below 30", summary:"A technical pullback screen for larger companies with low relative-strength readings.", criteria:["Large market capitalization","RSI below 30","Research screen, not a buy signal"], category:"pullback" },
  { slug:"growing-stocks-with-momentum", title:"Growing stocks with momentum", query:"Companies with positive revenue growth, positive one-week performance, and within 10% of their 52-week highs", summary:"Looks for revenue growth alongside recent price strength instead of relying on momentum alone.", criteria:["Positive revenue growth","Positive one-week price change","Within 10% of 52-week high"], category:"momentum" },
  { slug:"beaten-down-still-growing", title:"Beaten-down stocks that are still growing", query:"Stocks more than 15% below their 52-week highs that still have positive revenue growth", summary:"Separates price weakness from business contraction by requiring continued revenue growth.", criteria:["More than 15% below 52-week high","Positive revenue growth","Rankable by the size of the pullback"], category:"pullback" },
  { slug:"high-yield-value-stocks", title:"High-yield value stocks", query:"Dividend stocks yielding over 3% with a P/E under 20", summary:"An income screen that combines dividend yield with a simple earnings-valuation ceiling.", criteria:["Dividend yield above 3%","P/E below 20","Transparent filter interpretation"], category:"income" },
  { slug:"large-cap-value-stocks", title:"Large-cap value stocks", query:"Large companies with a P/E under 18 and price-to-book under 4", summary:"A broad value screen using two common valuation measures rather than a single ratio.", criteria:["Large market capitalization","P/E below 18","Price-to-book below 4"], category:"value" },
  { slug:"growing-tech-on-a-pullback", title:"Growing technology stocks on a pullback", query:"Technology companies with positive revenue growth more than 15% below their 52-week highs", summary:"Narrows pullback hunting to technology companies that are still growing revenue.", criteria:["Technology sector","Positive revenue growth","At least 15% below 52-week high"], category:"pullback" },
  { slug:"low-price-to-sales-growth-stocks", title:"Growth stocks with lower price-to-sales ratios", query:"Companies growing revenue more than 10% with a price-to-sales ratio under 5", summary:"Combines positive top-line growth with a cap on the price investors are paying for each dollar of sales.", criteria:["Revenue growth above 10%","Price-to-sales below 5","Editable thresholds"], category:"growth" },
  { slug:"revenue-growth-leaders", title:"Revenue growth leaders", query:"Large companies growing revenue more than 25% a year", summary:"A straightforward screen for larger companies posting rapid top-line expansion.", criteria:["Large market capitalization","Revenue growth above 25%","Editable growth threshold"], category:"growth" },
  { slug:"low-pe-growing-stocks", title:"Growing stocks with low P/E ratios", query:"Companies with positive revenue growth and a P/E below 12", summary:"A compact value screen that requires positive revenue growth alongside a low earnings multiple.", criteria:["Positive revenue growth","P/E below 12","Ranked by valuation if desired"], category:"value" },
  { slug:"dividend-growth-candidates", title:"Dividend growth candidates", query:"Dividend stocks yielding over 2% with positive revenue growth and beta below 1.2", summary:"Looks for dividend-paying companies that are still growing revenue without unusually high historical volatility.", criteria:["Dividend yield above 2%","Positive revenue growth","Beta below 1.2"], category:"income" },
  { slug:"stocks-near-52-week-highs", title:"Stocks near 52-week highs", query:"Large-cap stocks within 5% of their 52-week highs", summary:"A momentum screen for larger stocks trading close to their strongest prices of the past year.", criteria:["Large market capitalization","Within 5% of 52-week high","Momentum-oriented, not a recommendation"], category:"momentum" },
  { slug:"low-volatility-large-caps", title:"Low-volatility large caps", query:"Large-cap stocks with beta below 0.8", summary:"A simple screen for larger companies whose shares have historically been less volatile than the broad market.", criteria:["Large market capitalization","Beta below 0.8","Daily-refreshed market data"], category:"quality" },
  { slug:"strong-momentum-large-caps", title:"Large caps with strong momentum", query:"Large-cap stocks up more than 3% this week with RSI above 55", summary:"Combines recent weekly price strength with an above-neutral RSI reading.", criteria:["Large market capitalization","One-week change above 3%","RSI above 55"], category:"momentum" },
  { slug:"mega-cap-pullbacks", title:"Mega-cap pullbacks", query:"Very large companies more than 10% below their 52-week highs", summary:"Finds major companies that have pulled back meaningfully from their recent highs.", criteria:["Very large market capitalization","More than 10% below 52-week high","Rankable by pullback size"], category:"pullback" },
  { slug:"steady-growers-on-a-pullback", title:"Steady growers on a pullback", query:"Companies growing revenue more than 5%, with beta below 1.2, that are at least 10% below their 52-week highs", summary:"Combines continued revenue growth, moderate historical volatility, and a meaningful price pullback.", criteria:["Revenue growth above 5%","Beta below 1.2","At least 10% below 52-week high"], category:"quality" },
  { slug:"undervalued-growth-stocks", title:"Undervalued growth stocks", query:"Companies with positive revenue growth, a P/E under 20, and a price-to-book under 4", summary:"A blended screen for growth plus valuation discipline using both earnings and book-value ratios.", criteria:["Positive revenue growth","P/E below 20","Price-to-book below 4"], category:"growth" },
];

export function getPublicScreen(slug: string) { return PUBLIC_SCREENS.find((screen) => screen.slug === slug); }
