"use client";

import { useMemo, useState } from "react";
import type { PublicScreen } from "../../lib/publicScreens";

type CommunityScreen = { slug: string; title: string; query: string; createdAt?: string };
type Props = { screens: PublicScreen[]; community: CommunityScreen[] };

const T = { bg: "#F4F5F7", surface: "#FFFFFF", surfaceAlt: "#FAFBFC", border: "#E6E8EC", borderStrong: "#D4D8DF", ink: "#15171C", inkSoft: "#565C67", inkFaint: "#68707D", accent: "#2C36A8", accentSoft: "#ECEEFA", accentInk: "#232A85" };
const DISP = "var(--font-display), 'Instrument Sans', system-ui, sans-serif";
const MONO = "var(--font-mono), 'JetBrains Mono', ui-monospace, monospace";
const CATEGORIES = ["All", "Value", "Quality", "Growth", "Income", "Momentum", "Pullback"] as const;
const FEATURED = ["high-roic-companies", "quality-compounders", "high-fcf-yield", "strong-balance-sheets", "high-growth-reasonable-valuation", "high-dividend-low-volatility-stocks"];

export default function ScreenMarketplace({ screens, community }: Props) {
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");
  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    return screens.filter((screen) => {
      const categoryMatch = category === "All" || screen.category === category.toLowerCase();
      const haystack = [screen.title, screen.summary, screen.query, screen.category, ...screen.criteria].join(" ").toLowerCase();
      return categoryMatch && (!q || haystack.includes(q));
    }).sort((a, b) => Number(FEATURED.includes(b.slug)) - Number(FEATURED.includes(a.slug)));
  }, [screens, search, category]);

  return <div className="market-root">
    <style>{`
      .market-root{min-height:100vh;background:${T.bg};color:${T.ink};font-family:var(--font-body),'Inter',system-ui,sans-serif}.market-head{border-bottom:1px solid ${T.border};background:${T.bg}}.market-nav{max-width:1120px;margin:0 auto;padding:14px 24px;display:flex;align-items:center;justify-content:space-between}.market-main{max-width:1120px;margin:0 auto;padding:54px 24px 88px}.market-search{display:flex;align-items:center;gap:11px;background:${T.surface};border:1px solid ${T.borderStrong};border-radius:14px;padding:0 16px;height:52px;max-width:720px;box-shadow:0 1px 2px rgba(21,23,28,.04)}.market-search:focus-within{border-color:${T.accent};box-shadow:0 0 0 3px ${T.accentSoft}}.market-search input{border:0;outline:0;background:transparent;width:100%;font-size:15.5px;color:${T.ink}}.chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:17px}.chip{height:34px;padding:0 14px;border-radius:18px;border:1px solid ${T.border};background:${T.surface};color:${T.inkSoft};font-size:13.5px;cursor:pointer}.chip.active{background:${T.accent};border-color:${T.accent};color:#fff}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.card{display:flex;flex-direction:column;min-height:238px;background:${T.surface};border:1px solid ${T.border};border-radius:15px;padding:19px;text-decoration:none;color:${T.ink};transition:transform .14s,border-color .14s,box-shadow .14s}.card:hover{transform:translateY(-2px);border-color:${T.borderStrong};box-shadow:0 6px 18px rgba(21,23,28,.06)}.criteria{display:flex;gap:6px;flex-wrap:wrap;margin-top:14px}.criterion{font-family:${MONO};font-size:11.5px;background:${T.surfaceAlt};border:1px solid ${T.border};padding:5px 7px;border-radius:7px;color:${T.inkSoft}}.card-actions{margin-top:auto;padding-top:18px;display:flex;align-items:center;justify-content:space-between;gap:10px}.run{font-weight:600;color:${T.accent};font-size:13.5px}.customize{color:${T.inkSoft};font-size:12.5px}.badge{font-family:${MONO};font-size:10.5px;letter-spacing:.04em;text-transform:uppercase;color:${T.accent};background:${T.accentSoft};padding:5px 7px;border-radius:6px}.empty{background:${T.surface};border:1px dashed ${T.borderStrong};border-radius:14px;padding:34px;text-align:center;color:${T.inkSoft}}@media(max-width:900px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.grid{grid-template-columns:1fr}.market-main{padding-top:38px}.market-nav{padding:13px 18px}.market-main{padding-left:18px;padding-right:18px}.nav-investors{display:none}}
    `}</style>
    <header className="market-head"><div className="market-nav"><a href="/" style={{ color:T.ink,textDecoration:"none",fontFamily:DISP,fontWeight:650,fontSize:18 }}>Parse</a><div style={{display:"flex",gap:18,alignItems:"center",fontSize:14}}><a className="nav-investors" href="/investors" style={{color:T.inkSoft,textDecoration:"none"}}>Investor portfolios</a><a href="/try" style={{color:T.accent,textDecoration:"none",fontWeight:600}}>Build a screen →</a></div></div></header>
    <main className="market-main">
      <section style={{maxWidth:800}}><div style={{fontFamily:MONO,fontSize:12,color:T.accent,textTransform:"uppercase",letterSpacing:".07em",marginBottom:12}}>Screener marketplace</div><h1 style={{fontFamily:DISP,fontSize:"clamp(36px,5vw,52px)",lineHeight:1.03,letterSpacing:"-.035em",margin:"0 0 15px",fontWeight:620}}>Find a screen worth exploring.</h1><p style={{color:T.inkSoft,fontSize:16.5,lineHeight:1.6,maxWidth:700,margin:"0 0 28px"}}>Start with a proven idea, inspect exactly what it screens for, then make it yours with natural language.</p><div className="market-search"><span aria-hidden style={{color:T.inkFaint,fontSize:19}}>⌕</span><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search by strategy, metric, or idea…" aria-label="Search screeners" />{search && <button onClick={()=>setSearch("")} aria-label="Clear search" style={{border:0,background:"transparent",color:T.inkFaint,fontSize:18,cursor:"pointer"}}>×</button>}</div><div className="chips">{CATEGORIES.map((item)=><button key={item} className={`chip ${category===item?"active":""}`} onClick={()=>setCategory(item)}>{item}</button>)}</div></section>

      <section style={{marginTop:46}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",gap:16,marginBottom:15}}><h2 style={{fontFamily:DISP,fontSize:22,margin:0,fontWeight:620}}>{search || category!=="All" ? "Matching screeners" : "Popular screeners"}</h2><span style={{color:T.inkFaint,fontSize:13}}>{filtered.length} {filtered.length===1?"screen":"screens"}</span></div>{filtered.length ? <div className="grid">{filtered.map((screen,index)=><a className="card" key={screen.slug} href={`/screens/${screen.slug}`}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><span style={{fontFamily:MONO,fontSize:11.5,color:T.inkFaint,textTransform:"uppercase"}}>{screen.category}</span>{FEATURED.includes(screen.slug) && index<6 ? <span className="badge">Popular</span>:null}</div><h3 style={{fontFamily:DISP,fontSize:19,lineHeight:1.25,margin:"13px 0 8px",fontWeight:650}}>{screen.title}</h3><p style={{color:T.inkSoft,fontSize:13.5,lineHeight:1.5,margin:0}}>{screen.summary}</p><div className="criteria">{screen.criteria.slice(0,3).map((c)=><span className="criterion" key={c}>{c}</span>)}</div><div className="card-actions"><span className="run">Run screen →</span><span className="customize">Open & customize</span></div></a>)}</div> : <div className="empty">No screeners match that search yet. Try a metric like “ROIC”, “FCF”, “dividend”, or choose another category.</div>}</section>

      {community.length>0 && !search && category==="All" ? <section style={{marginTop:48}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",marginBottom:15}}><h2 style={{fontFamily:DISP,fontSize:22,margin:0,fontWeight:620}}>From the community</h2><span style={{color:T.inkFaint,fontSize:13}}>Recently published</span></div><div className="grid">{community.slice(0,6).map((screen)=><a className="card" style={{minHeight:170}} key={screen.slug} href={`/s/${screen.slug}`}><span style={{fontFamily:MONO,fontSize:11.5,color:T.inkFaint,textTransform:"uppercase"}}>Community</span><h3 style={{fontFamily:DISP,fontSize:18,margin:"12px 0 8px"}}>{screen.title}</h3>{screen.query && <p style={{color:T.inkSoft,fontSize:13.5,lineHeight:1.5,margin:0}}>{screen.query}</p>}<div className="card-actions"><span className="run">View exact screen →</span></div></a>)}</div></section>:null}

      <section style={{marginTop:52,padding:"28px 30px",background:T.accentSoft,border:"1px solid #DADEF6",borderRadius:16,display:"flex",justifyContent:"space-between",alignItems:"center",gap:24,flexWrap:"wrap"}}><div><h2 style={{fontFamily:DISP,fontSize:22,margin:"0 0 6px",fontWeight:650}}>Don’t see the screen you want?</h2><p style={{color:T.inkSoft,margin:0,fontSize:14.5}}>Describe it in plain English. Parse will turn it into editable criteria.</p></div><a href="/try" style={{display:"inline-flex",alignItems:"center",height:42,padding:"0 18px",background:T.accent,color:"#fff",borderRadius:10,textDecoration:"none",fontWeight:600,fontSize:14}}>Build your own →</a></section>
    </main>
  </div>;
}
