import type { Metadata } from "next";
import { decodeScreenState } from "../../../lib/screen-state";
import { FIELDS } from "../../../lib/fields";

const T = { bg: "#F4F5F7", surface: "#FFFFFF", border: "#E6E8EC", ink: "#15171C", inkSoft: "#565C67", accent: "#2C36A8" };
const DISP = "var(--font-display), 'Instrument Sans', system-ui, sans-serif";
const MONO = "var(--font-mono), 'JetBrains Mono', ui-monospace, monospace";
function rawState(searchParams: { state?: string | string[] }) { const r = Array.isArray(searchParams.state) ? searchParams.state[0] : searchParams.state; return r || ""; }
export function generateMetadata(): Metadata { return { title: "Shared stock screen", description: "Open an exact stock screen shared from Parse.", robots: { index: false, follow: true } }; }
export default function SharedScreenPage({ searchParams }: { searchParams: { state?: string | string[] } }) {
  const raw = rawState(searchParams); const state = decodeScreenState(raw); const tryUrl = state ? `/try?state=${raw}&source=shared_screen` : "/try";
  return <div style={{ minHeight: "100vh", background: T.bg, color: T.ink, fontFamily: "var(--font-body), 'Inter', system-ui, sans-serif" }}><header style={{ borderBottom: `1px solid ${T.border}` }}><div style={{ maxWidth: 840, margin: "0 auto", padding: "14px 24px" }}><a href="/" style={{ color: T.ink, textDecoration: "none", fontFamily: DISP, fontWeight: 600, fontSize: 18 }}>Parse</a></div></header><main style={{ maxWidth: 840, margin: "0 auto", padding: "60px 24px 84px" }}><div style={{ color: T.accent, fontSize: 12, fontWeight: 650, letterSpacing: ".06em", marginBottom: 12 }}>SHARED SCREEN</div><h1 style={{ fontFamily: DISP, fontSize: 36, margin: "0 0 12px" }}>{state?.q || "An exact stock screen from Parse"}</h1><p style={{ color: T.inkSoft, lineHeight: 1.55 }}>This link preserves the actual filters and ranking—not just the sentence that originally created them.</p>{state ? <section style={{ marginTop: 24, background: T.surface, border: `1px solid ${T.border}`, borderRadius: 15, padding: 20 }}><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{state.filters.map((f) => { const m = FIELDS[f.field]; return <span key={f.id} style={{ fontFamily: MONO, fontSize: 12.5, padding: "7px 9px", border: `1px solid ${T.border}`, borderRadius: 8 }}>{m?.label || f.field} {f.op} {String(f.value)}</span>; })}</div><a href={tryUrl} style={{ display: "inline-flex", height: 42, alignItems: "center", marginTop: 20, padding: "0 18px", borderRadius: 10, background: T.accent, color: "#fff", textDecoration: "none", fontWeight: 550 }}>Open and edit this screen</a></section> : <p>No valid screen was included in this link.</p>}</main></div>;
}
